jbosstools/jbosstools-base

- common/plugins/org.jboss.tools.common.ui/src/org/jboss/tools/common/ui/JobUtils.java
- common/tests/org.jboss.tools.common.ui.test/src/org/jboss/tools/common/ui/CommonUITestSuite.java
- common/tests/org.jboss.tools.common.ui.test/src/org/jboss/tools/common/ui/JobUtilsTest.java
> [JBIDE-19689] Add isWarning to JobUtils

- common/plugins/org.jboss.tools.common.core/META-INF/MANIFEST.MF
- common/plugins/org.jboss.tools.common.core/src/org/jboss/tools/common/core/jandex/JandexUtil.java
- common/tests/org.jboss.tools.common.core.test/src/org/jboss/tools/common/core/test/JandexTest.java
Jandex API is incapsulated in common plugin.
Public query methods are added.
> JBIDE-19820 Batch feature makes wildfly import way slower

- common/plugins/org.jboss.tools.common.model.ui/src/org/jboss/tools/common/editor/ObjectMultiPageEditor.java
- common/plugins/org.jboss.tools.common.text.ext/src/org/jboss/tools/common/text/ext/IMultiPageEditor.java
- common/plugins/org.jboss.tools.common.text.ext/src/org/jboss/tools/common/text/ext/hyperlink/xpl/AbstractBaseHyperlink.java
- common/plugins/org.jboss.tools.common.text.ext/src/org/jboss/tools/common/text/ext/util/StructuredSelectionHelper.java
OpenOn on Batch Property which shows Batch Property references
> JBIDE-19700 Support @BatchProperty qualifiers for injected beans

- common/plugins/org.jboss.tools.common.validation/src/org/jboss/tools/common/validation/ValidationErrorManager.java
- common/plugins/org.jboss.tools.common/src/org/jboss/tools/common/quickfix/AbstractQuickFixGenerator.java
Created AbstractQuickFixGenerator.java with methods
> JBIDE-19266 Batch validation problems QuickFixes

- common/tests/org.jboss.tools.common.model.ui.test/src/org/jboss/tools/common/model/ui/test/ModelUiAllTests.java
- common/tests/org.jboss.tools.common.text.ext.test/src/org/jboss/tools/common/text/ext/test/TextExtAllTests.java
- common/tests/org.jboss.tools.common.verification.ui.test/src/org/jboss/tools/common/verification/ui/test/VerificationUiAllTests.java
- common/tests/org.jboss.tools.common.verification.ui.test/src/org/jboss/tools/common/verification/ui/vrules/preferences/test/VerificationPreferencePageTest.java
- tests/plugins/org.jboss.tools.tests/src/org/jboss/tools/tests/PreferencePageTest.java
Conflicts:
common/tests/org.jboss.tools.common.text.ext.test/src/org/jboss/tools/common/text/ext/test/TextExtAllTests.java
> JBIDE-20689 Skip tests that cannot run on current platform

- common/plugins/org.jboss.tools.common.ui/src/org/jboss/tools/common/ui/widget/editor/SwtFieldEditorFactory.java
Migrate to Neon M3 development release
> JBIDE-20976 Create and use Neon M3 target platform

- foundation/plugins/org.jboss.tools.foundation.help.ui/src/org/jboss/tools/foundation/help/ui/internal/search/SearchiskoResultBuilder.java
- foundation/tests/org.jboss.tools.foundation.help.test/src/org/jboss/tools/foundation/help/ui/internal/search/SearchiskoEngineTest.java
Signed-off-by: Fred Bricon <fbricon@gmail.com>
> JBIDE-22458 : JBoss Help should use DCP v2

- foundation/tests/org.jboss.tools.foundation.core.test/pom.xml
- foundation/tests/org.jboss.tools.foundation.ui.test/src/org/jboss/tools/foundation/ui/test/WidgetUtilityTest.java
- foundation/tests/pom.xml
- pom.xml
Signed-off-by: Fred Bricon <fbricon@gmail.com>
> JBIDE-19081 remove foundation test pattern restrictions

- foundation/tests/org.jboss.tools.foundation.ui.test/src/org/jboss/tools/foundation/ui/test/BrowserUtilTest.java
- runtime/plugins/org.jboss.tools.runtime.ui/META-INF/MANIFEST.MF
- runtime/plugins/org.jboss.tools.runtime.ui/src/org/jboss/tools/runtime/ui/internal/startup/RuntimeScanner.java
- runtime/tests/org.jboss.tools.runtime.test/META-INF/MANIFEST.MF
- runtime/tests/org.jboss.tools.runtime.test/src/org/jboss/tools/runtime/test/RuntimeDetectionFrameworkTest.java
not for push to master. purely for debugging.
> Testfailuresv3

- usage/tests/org.jboss.tools.usage.test/build.properties
- usage/tests/org.jboss.tools.usage.test/src/org/jboss/tools/usage/test/UsageBrandingTest.java
* Generify UsageBrandingTest.
* clean-up src/bin.includes.
> Cleanup warnings.

- all-tests/pom.xml
> [JBIDE-23642] - Bump versions (#544)

- common/plugins/org.jboss.tools.common.validation/src/org/jboss/tools/common/validation/TempMarkerManager.java
This issue is the top one reported by aeri. Already 275 reports by half of the year.
I was unable to reproduce it. However, i found some similar issues and linked them to this one. My changes are based on 1 of them: [JBIDE-13076](https://issues.jboss.org/browse/JBIDE-13076) and [it's fix](https://github.com/jbosstools/jbosstools-base/pull/28/files)
> jbide-22891: check existence of the marker

- common/plugins/org.jboss.tools.common.model.ui/src/org/jboss/tools/common/model/ui/navigator/decorator/DecoratorManager.java
- common/plugins/org.jboss.tools.common.model/src/org/jboss/tools/common/model/loaders/impl/ModelEntityRecognizer.java
- common/plugins/org.jboss.tools.common.validation/META-INF/MANIFEST.MF
- common/plugins/org.jboss.tools.common.validation/src/org/jboss/tools/common/validation/TempMarkerManager.java
- common/plugins/org.jboss.tools.common.validation/src/org/jboss/tools/common/validation/internal/ProjectValidationContext.java
- common/plugins/org.jboss.tools.common.validation/src/org/jboss/tools/common/validation/java/JavaDirtyRegionProcessor.java
it improves performance
Signed-off-by: Aurelien Pupier <apupier@redhat.com>
> Iterate over the "entrySet" instead of the "keySet"

- common/test-framework/org.jboss.tools.common.reddeer/META-INF/MANIFEST.MF
- common/test-framework/org.jboss.tools.common.reddeer/src/org/jboss/tools/common/reddeer/perspectives/JBossPerspective.java
- common/test-framework/org.jboss.tools.common.reddeer/src/org/jboss/tools/common/reddeer/preferences/SourceLookupPreferencePage.java
- common/test-framework/org.jboss.tools.common.reddeer/src/org/jboss/tools/common/reddeer/propertieseditor/PropertiesEditor.java
- common/test-framework/org.jboss.tools.common.reddeer/src/org/jboss/tools/common/reddeer/propertieseditor/PropertiesSourceEditor.java
- common/test-framework/org.jboss.tools.common.reddeer/src/org/jboss/tools/common/reddeer/requirements/JavaFoldingRequirement.java
- common/test-framework/org.jboss.tools.common.reddeer/src/org/jboss/tools/common/reddeer/utils/ProjectHelper.java
- common/test-framework/org.jboss.tools.common.reddeer/src/org/jboss/tools/common/reddeer/utils/ResourceLookup.java
- runtime/test-framework/org.jboss.tools.runtime.reddeer/META-INF/MANIFEST.MF
- runtime/test-framework/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/condition/RuntimeIsDownloading.java
- runtime/test-framework/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/wizard/DownloadRuntimesTaskWizard.java
- runtime/test-framework/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/wizard/TaskWizardFirstPage.java
- runtime/test-framework/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/wizard/TaskWizardLoginPage.java
- runtime/test-framework/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/wizard/TaskWizardSecondPage.java
- runtime/test-framework/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/wizard/TaskWizardThirdPage.java
Signed-off-by: Rastislav Wagner <rawagner@redhat.com>
> Refactor test-framework plugins to use RedDeer2

- runtime/plugins/org.jboss.tools.runtime.core/src/org/jboss/tools/runtime/core/util/internal/DownloadRuntimeOperationUtility.java
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
> JBIDE-25098 - ensure stacktrace is preserved

- foundation/features/org.jboss.tools.foundation.feature/pom.xml
- foundation/features/org.jboss.tools.foundation.license.feature/feature.xml
- foundation/features/org.jboss.tools.foundation.license.feature/pom.xml
- foundation/features/org.jboss.tools.foundation.security.linux.feature/feature.xml
- foundation/features/org.jboss.tools.foundation.security.linux.feature/pom.xml
- foundation/features/org.jboss.tools.foundation.test.feature/feature.xml
- foundation/features/org.jboss.tools.foundation.test.feature/pom.xml
- foundation/features/pom.xml
- foundation/plugins/org.jboss.tools.foundation.checkup/META-INF/MANIFEST.MF
- foundation/plugins/org.jboss.tools.foundation.checkup/pom.xml
- foundation/plugins/org.jboss.tools.foundation.core/pom.xml
- foundation/plugins/org.jboss.tools.foundation.help.ui/META-INF/MANIFEST.MF
- foundation/plugins/org.jboss.tools.foundation.help.ui/pom.xml
- foundation/plugins/org.jboss.tools.foundation.security.linux/META-INF/MANIFEST.MF
- foundation/plugins/org.jboss.tools.foundation.security.linux/pom.xml
- foundation/plugins/org.jboss.tools.foundation.ui/META-INF/MANIFEST.MF
- foundation/plugins/org.jboss.tools.foundation.ui/pom.xml
- foundation/plugins/org.jboss.tools.foundation.ui/src/org/jboss/tools/foundation/ui/credentials/ChooseCredentialComponent.java
- foundation/plugins/pom.xml
- foundation/pom.xml
- foundation/tests/org.jboss.tools.foundation.checkup.test/META-INF/MANIFEST.MF
- foundation/tests/org.jboss.tools.foundation.checkup.test/pom.xml
- foundation/tests/org.jboss.tools.foundation.core.test/META-INF/MANIFEST.MF
- foundation/tests/org.jboss.tools.foundation.core.test/pom.xml
- foundation/tests/org.jboss.tools.foundation.help.test/META-INF/MANIFEST.MF
- foundation/tests/org.jboss.tools.foundation.help.test/pom.xml
- foundation/tests/org.jboss.tools.foundation.ui.test/META-INF/MANIFEST.MF
- foundation/tests/org.jboss.tools.foundation.ui.test/pom.xml
- foundation/tests/pom.xml
> JBIDE-25261 - credential edit button enabled with no selection

- foundation/plugins/org.jboss.tools.foundation.ui/src/org/jboss/tools/foundation/ui/credentials/ChooseCredentialComponent.java
> JBDS-4668 - Add NPE check to download runtimes

- usage/features/org.jboss.tools.usage.feature/feature.xml
- usage/features/org.jboss.tools.usage.feature/pom.xml
- usage/features/org.jboss.tools.usage.test.feature/feature.xml
- usage/features/org.jboss.tools.usage.test.feature/pom.xml
- usage/features/pom.xml
- usage/plugins/org.jboss.tools.usage/META-INF/MANIFEST.MF
- usage/plugins/org.jboss.tools.usage/build.properties
- usage/plugins/org.jboss.tools.usage/pom.xml
- usage/plugins/pom.xml
- usage/pom.xml
- usage/tests/org.jboss.tools.usage.test/META-INF/MANIFEST.MF
- usage/tests/org.jboss.tools.usage.test/pom.xml
- usage/tests/pom.xml
> [JBIDE-25676] - Missing image for Jboss Tools Aeri

- runtime/plugins/org.jboss.tools.runtime.ui/src/org/jboss/tools/runtime/ui/DownloadRuntimeMessages.properties
- runtime/plugins/org.jboss.tools.runtime.ui/src/org/jboss/tools/runtime/ui/internal/wizard/workflow/DownloadManagerCredentialsFragment.java
- runtime/plugins/org.jboss.tools.runtime.ui/src/org/jboss/tools/runtime/ui/internal/wizard/workflow/DownloadManagerWorkflowUtility.java
> JBIDE-25664 - read error messages from download connection

- runtime/test-framework/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/wizard/TaskWizardLoginPage.java
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>
> JBIDE-25694 Add missing functionality to RedDeer plugin

- common/plugins/org.jboss.tools.common.jdt.debug/src/org/jboss/tools/common/jdt/debug/JavaUtilities.java
- common/plugins/org.jboss.tools.common.jdt.debug/src/org/jboss/tools/common/jdt/debug/tools/ToolsCore.java
- common/plugins/org.jboss.tools.common.jdt.debug/src/org/jboss/tools/common/jdt/debug/tools/internal/PreJigsawUtility.java
- common/plugins/org.jboss.tools.common.jdt.debug/src/org/jboss/tools/common/jdt/debug/tools/internal/Tools.java
> JBIDE-25556 - initial fix for java9 / jigsaw

- common/plugins/org.jboss.tools.common.jdt.debug/src/org/jboss/tools/common/jdt/debug/JavaUtilities.java
> JBIDE-25864 - bad code leads to array index error

- usage/features/org.jboss.tools.usage.feature/feature.xml
- usage/features/org.jboss.tools.usage.feature/pom.xml
- usage/features/org.jboss.tools.usage.test.feature/feature.xml
- usage/features/org.jboss.tools.usage.test.feature/pom.xml
- usage/features/pom.xml
- usage/plugins/org.jboss.tools.usage/META-INF/MANIFEST.MF
- usage/plugins/org.jboss.tools.usage/pom.xml
- usage/plugins/org.jboss.tools.usage/src/org/jboss/tools/usage/internal/JBossToolsUsageActivator.java
- usage/plugins/pom.xml
- usage/pom.xml
- usage/tests/org.jboss.tools.usage.test/META-INF/MANIFEST.MF
- usage/tests/org.jboss.tools.usage.test/pom.xml
- usage/tests/pom.xml
> [JBDS-4697] - Circular reference detected trying to get service

- foundation/tests/org.jboss.tools.foundation.core.test/META-INF/MANIFEST.MF
> [JBIDE-25944] - Adapt base for Photon

- runtime/plugins/org.jboss.tools.runtime.core/src/org/jboss/tools/runtime/core/model/internal/BinaryInstaller.java
> JBIDE-25968 - if file.renameTo fails, try to copy it

- runtime/plugins/org.jboss.tools.runtime.core/src/org/jboss/tools/runtime/core/model/internal/BinaryInstaller.java
> [JBIDE-26100] - base does not compile on JDK9/10

- common/test-framework/org.jboss.tools.common.reddeer/META-INF/MANIFEST.MF
RedDeer plugin org.jboss.tools.common.reddeer
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>
> JBIDE-26282 Updated Bundle-RequiredExecutionEnvironment to JavaSE-1.8 in

- common/tests/org.jboss.tools.common.mylyn.test/META-INF/MANIFEST.MF
- stacks/tests/org.jboss.tools.stacks.core.test/META-INF/MANIFEST.MF
> JBIDE-26471 - Fix test errors on Java11+

- common/plugins/org.jboss.tools.common.jaxb/META-INF/MANIFEST.MF
> JBIDE-26500 - central test errors on Java11+

- common/plugins/org.jboss.tools.common.jdt.debug/src/org/jboss/tools/common/jdt/debug/JavaUtilities.java
- common/plugins/org.jboss.tools.common.jdt.debug/src/org/jboss/tools/common/jdt/debug/tools/ToolsCore.java
- common/plugins/org.jboss.tools.common.jdt.debug/src/org/jboss/tools/common/jdt/debug/tools/internal/IToolsConstants.java
- common/plugins/org.jboss.tools.common.jdt.debug/src/org/jboss/tools/common/jdt/debug/tools/internal/Tools.java
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
> JBIDE-26598 - provide utilities to know if targeted VM is running Jigsaw

- common/plugins/org.jboss.tools.common/src/org/jboss/tools/common/util/DownloadHelper.java
> JBIDE-26993: Provide download infrastructure for cli

- common/plugins/org.jboss.tools.common.projecttemplates/templates/JSFVersions.xml
- common/plugins/org.jboss.tools.common.projecttemplates/templates/jsf-2.3/JSFBlankWithoutLibs/.preprocessing
- common/plugins/org.jboss.tools.common.projecttemplates/templates/jsf-2.3/JSFBlankWithoutLibs/WebContent/WEB-INF/faces-config.xml
- common/plugins/org.jboss.tools.common.projecttemplates/templates/jsf-2.3/JSFBlankWithoutLibs/WebContent/WEB-INF/web.xml
- common/plugins/org.jboss.tools.common.projecttemplates/templates/jsf-2.3/JSFKickStartWithoutLibs/.preprocessing
- common/plugins/org.jboss.tools.common.projecttemplates/templates/jsf-2.3/JSFKickStartWithoutLibs/JavaSource/demo/User.java
- common/plugins/org.jboss.tools.common.projecttemplates/templates/jsf-2.3/JSFKickStartWithoutLibs/JavaSource/resources.properties
- common/plugins/org.jboss.tools.common.projecttemplates/templates/jsf-2.3/JSFKickStartWithoutLibs/WebContent/WEB-INF/.faces-config.xml.jsfdia
- common/plugins/org.jboss.tools.common.projecttemplates/templates/jsf-2.3/JSFKickStartWithoutLibs/WebContent/WEB-INF/faces-config.xml
- common/plugins/org.jboss.tools.common.projecttemplates/templates/jsf-2.3/JSFKickStartWithoutLibs/WebContent/WEB-INF/web.xml
- common/plugins/org.jboss.tools.common.projecttemplates/templates/jsf-2.3/JSFKickStartWithoutLibs/WebContent/index.html
- common/plugins/org.jboss.tools.common.projecttemplates/templates/jsf-2.3/JSFKickStartWithoutLibs/WebContent/pages/greeting.xhtml
- common/plugins/org.jboss.tools.common.projecttemplates/templates/jsf-2.3/JSFKickStartWithoutLibs/WebContent/pages/inputname.xhtml
- common/plugins/org.jboss.tools.common.projecttemplates/templates/jsf-2.3/JSFKickStartWithoutLibs/WebContent/resources/demo/input.xhtml
- common/plugins/org.jboss.tools.common.projecttemplates/templates/jsf-2.3/JSFKickStartWithoutLibs/WebContent/templates/common.xhtml
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>
> JBIDE-27067 Add JSF 2.3 project templates

- foundation/plugins/org.jboss.tools.foundation.core/src/org/jboss/tools/foundation/core/ecf/internal/InternalURLTransport.java
- foundation/plugins/org.jboss.tools.foundation.core/src/org/jboss/tools/foundation/core/properties/internal/VersionPropertiesProvider.java
- foundation/tests/org.jboss.tools.foundation.core.test/src/org/jboss/tools/foundation/core/properties/mock/MockDevStudioPropertiesProvider.java
- foundation/tests/org.jboss.tools.foundation.core.test/src/org/jboss/tools/foundation/core/test/ecf/URLTransportUtilTest.java
> [JBIDE-27073] Add user agent string to request headers

- foundation/plugins/org.jboss.tools.foundation.core/src/org/jboss/tools/foundation/core/properties/internal/currentversion.properties
> JBIDE-27162: Fix properties for 4.15.0.Final / 12.15.0.GA

- foundation/plugins/org.jboss.tools.foundation.core/src/org/jboss/tools/foundation/core/properties/internal/currentversion.properties
> Bump default version to 4.16.0.AM1

- common/plugins/org.jboss.tools.common.text.xml/src/org/jboss/tools/common/text/xml/XMLTextViewerConfiguration.java
> JBIDE-27304 : fix build

- foundation/plugins/org.jboss.tools.foundation.core/src/org/jboss/tools/foundation/core/properties/internal/currentversion.properties
> Bump default version to 4.16.0.Final

- common/plugins/org.jboss.tools.common.meta.ui/src/org/jboss/tools/common/meta/ui/attribute/editor/PropertiesStringFieldEditor.java
- common/plugins/org.jboss.tools.common.model.ui/src/org/jboss/tools/common/model/ui/attribute/adapter/AdapterFactory.java
- common/plugins/org.jboss.tools.common.model.ui/src/org/jboss/tools/common/model/ui/attribute/adapter/DefaultComboBoxValueAdapter.java
- common/plugins/org.jboss.tools.common.model.ui/src/org/jboss/tools/common/model/ui/attribute/editor/ComboBoxCellEditorEx.java
- common/plugins/org.jboss.tools.common.model.ui/src/org/jboss/tools/common/model/ui/attribute/editor/ListStructuredFieldEditor.java
- common/plugins/org.jboss.tools.common.model.ui/src/org/jboss/tools/common/model/ui/attribute/editor/MutableComboBoxFieldEditor.java
- common/plugins/org.jboss.tools.common.model.ui/src/org/jboss/tools/common/model/ui/attribute/editor/NoteFieldEditor.java
- common/plugins/org.jboss.tools.common.model.ui/src/org/jboss/tools/common/model/ui/attribute/editor/StringButtonFieldEditor.java
- common/plugins/org.jboss.tools.common.model.ui/src/org/jboss/tools/common/model/ui/dialog/MessageAndCheckboxDialog.java
- common/plugins/org.jboss.tools.common.text.xml/src/org/jboss/tools/jst/jsp/text/xpl/StructuredTextOccurrenceStructureProviderDescriptor.java
> JBIDE-27244: refactor imports

- jacoco-report/pom.xml
- runtime/features/org.jboss.tools.runtime.core.feature/feature.xml
- runtime/features/org.jboss.tools.runtime.core.feature/pom.xml
- runtime/features/org.jboss.tools.runtime.test.feature/feature.xml
- runtime/features/org.jboss.tools.runtime.test.feature/pom.xml
- runtime/features/pom.xml
- runtime/plugins/org.jboss.tools.runtime.core/META-INF/MANIFEST.MF
- runtime/plugins/org.jboss.tools.runtime.core/pom.xml
- runtime/plugins/org.jboss.tools.runtime.ui/META-INF/MANIFEST.MF
- runtime/plugins/org.jboss.tools.runtime.ui/pom.xml
- runtime/plugins/org.jboss.tools.runtime.ui/src/org/jboss/tools/runtime/ui/internal/dialogs/FastProgressMonitorFocusJobDialog.java
- runtime/plugins/pom.xml
- runtime/pom.xml
- runtime/test-framework/org.jboss.tools.runtime.reddeer/META-INF/MANIFEST.MF
- runtime/test-framework/org.jboss.tools.runtime.reddeer/pom.xml
- runtime/test-framework/pom.xml
- runtime/tests/org.jboss.tools.runtime.test/META-INF/MANIFEST.MF
- runtime/tests/org.jboss.tools.runtime.test/pom.xml
- runtime/tests/pom.xml
> fix build issues for 4.17.0.AM1

- foundation/plugins/org.jboss.tools.foundation.ui/src/org/jboss/tools/foundation/ui/credentials/ChooseCredentialOverridePasswordComponent.java
> NPE on environment change, not very reproduceable

- common/plugins/org.jboss.tools.common.oauth.core/src/org/jboss/tools/common/oauth/core/AccountService.java
- common/plugins/org.jboss.tools.common.oauth.core/src/org/jboss/tools/common/oauth/core/LoginResponse.java
- common/plugins/org.jboss.tools.common.oauth.core/src/org/jboss/tools/common/oauth/core/TokenProvider.java
- common/plugins/org.jboss.tools.common.oauth.core/src/org/jboss/tools/common/oauth/core/model/IAccount.java
- common/plugins/org.jboss.tools.common.oauth.core/src/org/jboss/tools/common/oauth/internal/core/DefaultTokenProvider.java
- common/plugins/org.jboss.tools.common.oauth.core/src/org/jboss/tools/common/oauth/internal/core/model/Account.java
- common/plugins/org.jboss.tools.common.oauth.ui/src/org/jboss/tools/common/oauth/internal/ui/BrowserBasedLoginDialog.java
- common/plugins/org.jboss.tools.common.oauth.ui/src/org/jboss/tools/common/oauth/internal/ui/DefaultLoginProvider.java
- common/plugins/org.jboss.tools.common.oauth.ui/src/org/jboss/tools/common/oauth/internal/ui/OAuthBrowser.java
- common/plugins/org.jboss.tools.common.ui/src/org/jboss/tools/common/ui/WizardUtils.java
- common/plugins/org.jboss.tools.common/src/org/jboss/tools/common/util/SwtUtil.java
- Review OAuth framework to return IDToken
- Returned token can be IDToken (default), access token or refresh token
- Add a new method to SwtUtil to deal with top shell and optimum size
> JBIDE-27680: Login/bootstrap Developer Sandbox

- foundation/plugins/org.jboss.tools.foundation.core/src/org/jboss/tools/foundation/core/properties/internal/currentversion.properties
> Bump default version to 4.19.0.Final

- foundation/plugins/org.jboss.tools.foundation.core/src/org/jboss/tools/foundation/core/properties/internal/currentversion.properties
> Bump default version to 4.19.1.Final

- jacoco-report/pom.xml
- stacks/features/org.jboss.tools.stacks.core.feature/feature.xml
- stacks/features/org.jboss.tools.stacks.core.feature/pom.xml
- stacks/features/org.jboss.tools.stacks.core.test.feature/feature.xml
- stacks/features/org.jboss.tools.stacks.core.test.feature/pom.xml
- stacks/features/pom.xml
- stacks/plugins/org.jboss.tools.stacks.core/.classpath
- stacks/plugins/org.jboss.tools.stacks.core/META-INF/MANIFEST.MF
- stacks/plugins/org.jboss.tools.stacks.core/pom.xml
- stacks/plugins/pom.xml
- stacks/pom.xml
- stacks/tests/org.jboss.tools.stacks.core.test/META-INF/MANIFEST.MF
- stacks/tests/org.jboss.tools.stacks.core.test/pom.xml
- stacks/tests/pom.xml
> JBIDE-27875: use httpClient 4 from TP

- .github/workflows/build_test.yml
> JBIDE-27835: revert temporary fix for baseline comparison

- foundation/tests/org.jboss.tools.foundation.core.test/META-INF/MANIFEST.MF
> JBIDE-27995: Replace JEE dependencies by Jakarta dependencies

- foundation/plugins/org.jboss.tools.foundation.core/src/org/jboss/tools/foundation/core/properties/internal/currentversion.properties
> Bump default version to 4.21.0.Final

- common/plugins/org.jboss.tools.common.oauth.ui/META-INF/MANIFEST.MF
- common/plugins/org.jboss.tools.common.oauth.ui/src/org/jboss/tools/common/oauth/internal/ui/OAuthBrowser.java
- foundation/plugins/org.jboss.tools.foundation.ui/META-INF/MANIFEST.MF
- foundation/plugins/org.jboss.tools.foundation.ui/src/org/jboss/tools/foundation/ui/util/BrowserUtility.java
fixes https://issues.redhat.com/browse/JBIDE-28000
> JBIDE-28000: move #allowNonHttpsRedirects to BrowserUtility (was:OAuthBrowser)

- foundation/plugins/org.jboss.tools.foundation.ui/src/org/jboss/tools/foundation/ui/util/AppleTransportSecurity.java
- foundation/plugins/org.jboss.tools.foundation.ui/src/org/jboss/tools/foundation/ui/util/BrowserUtility.java
This PR introduces a warning that informs Mac users about an exception to the default security policy (non-https connections are forbidden).
> warn user about sec exception to allow non-https

- jacoco-report/pom.xml
- usage/features/org.jboss.tools.usage.feature/feature.xml
- usage/features/org.jboss.tools.usage.feature/pom.xml
- usage/features/org.jboss.tools.usage.test.feature/feature.xml
- usage/features/org.jboss.tools.usage.test.feature/pom.xml
- usage/features/pom.xml
- usage/plugins/org.jboss.tools.usage/META-INF/MANIFEST.MF
- usage/plugins/org.jboss.tools.usage/pom.xml
- usage/plugins/org.jboss.tools.usage/src/org/jboss/tools/usage/internal/reporting/JBossToolsComponents.java
- usage/plugins/pom.xml
- usage/pom.xml
- usage/tests/org.jboss.tools.usage.test/META-INF/MANIFEST.MF
- usage/tests/org.jboss.tools.usage.test/pom.xml
- usage/tests/pom.xml
> JBIDE-28099: fix openshift telemetry usage (installs)

- usage/plugins/org.jboss.tools.usage/src/org/jboss/tools/usage/internal/reporting/JBossToolsComponents.java
> JBIDE-28098 : add quarkus telemetry usage (installs)

- foundation/plugins/org.jboss.tools.foundation.core/src/org/jboss/tools/foundation/core/properties/internal/currentversion.properties
> Prepare 4.21.2.AM1

- pom.xml
> JBIDE-28222: base is using http repository

- foundation/plugins/org.jboss.tools.foundation.core/src/org/jboss/tools/foundation/core/properties/internal/currentversion.properties
> Prepare 4.21.3.Final

- usage/plugins/org.jboss.tools.usage/src/org/jboss/tools/usage/util/HttpEncodingUtils.java
> fix unit tests failures while accessing to jboss.org URL

- jacoco-report/pom.xml
- runtime/features/org.jboss.tools.runtime.core.feature/feature.xml
- runtime/features/org.jboss.tools.runtime.core.feature/pom.xml
- runtime/features/org.jboss.tools.runtime.test.feature/feature.xml
- runtime/features/org.jboss.tools.runtime.test.feature/pom.xml
- runtime/features/pom.xml
- runtime/plugins/org.jboss.tools.runtime.core/META-INF/MANIFEST.MF
- runtime/plugins/org.jboss.tools.runtime.core/pom.xml
- runtime/plugins/org.jboss.tools.runtime.ui/META-INF/MANIFEST.MF
- runtime/plugins/org.jboss.tools.runtime.ui/pom.xml
- runtime/plugins/org.jboss.tools.runtime.ui/src/org/jboss/tools/runtime/ui/internal/wizard/workflow/DownloadManagerWorkflowUtility.java
- runtime/plugins/pom.xml
- runtime/pom.xml
- runtime/test-framework/org.jboss.tools.runtime.reddeer/META-INF/MANIFEST.MF
- runtime/test-framework/org.jboss.tools.runtime.reddeer/pom.xml
- runtime/test-framework/pom.xml
- runtime/tests/org.jboss.tools.runtime.test/META-INF/MANIFEST.MF
- runtime/tests/org.jboss.tools.runtime.test/pom.xml
- runtime/tests/pom.xml
> Fix #JBIDE-28330 - respond to status code 301 as an acceptance

- common/plugins/org.jboss.tools.common.core/.classpath
- common/plugins/org.jboss.tools.common.core/META-INF/MANIFEST.MF
- foundation/plugins/org.jboss.tools.foundation.core/.classpath
- foundation/plugins/org.jboss.tools.foundation.core/META-INF/MANIFEST.MF
- foundation/tests/org.jboss.tools.foundation.core.test/src/org/jboss/tools/foundation/core/test/ecf/URLTransportUtilTest.java
> JBIDE-28353: fix build after 4.23.0.AM1 TP update

- foundation/plugins/org.jboss.tools.foundation.core/src/org/jboss/tools/foundation/core/ecf/internal/InternalURLTransport.java
- foundation/tests/org.jboss.tools.foundation.core.test/.classpath
- foundation/tests/org.jboss.tools.foundation.core.test/META-INF/MANIFEST.MF
- foundation/tests/org.jboss.tools.foundation.core.test/src/org/jboss/tools/foundation/core/test/ecf/URLTransportUtilTest.java
> JBIDE-28356: fix timeout issue

- runtime/plugins/org.jboss.tools.runtime.ui/src/org/jboss/tools/runtime/ui/internal/wizard/DownloadRuntimeLicenseFragment.java
> Fixes #26856 - show license url

- foundation/plugins/org.jboss.tools.foundation.core/src/org/jboss/tools/foundation/core/properties/internal/currentversion.properties
> prepare 4.23.0.Final

- foundation/plugins/org.jboss.tools.foundation.core/src/org/jboss/tools/foundation/core/properties/internal/currentversion.properties
> prepare 4.24.0.Final

- foundation/plugins/org.jboss.tools.foundation.core/src/org/jboss/tools/foundation/core/properties/internal/currentversion.properties
> Prepare for 4.26.0.Final
